import random

EXCUSES = [
    "Floating point emotions",
    "Quantum interference",
    "Cosmic rays",
    "Skill issue",
    "Math had a bad day",
    "Blame the compiler",
    "Syntax felt rebellious",
    "Random number said no",
    "Gravity is too strong",
    "Aliens moved the decimal",
    "Time dilation error",
    "Entropy wins again",
    "Cache forgot my homework",
    "The universe is debugging me",
    "Stack overflow in life",
    "CPU went on vacation",
    "Logic refused to cooperate",
    "Black hole swallowed the answer",
    "Pi is irrational today",
    "Godmode not enabled",
    "Lost in an infinite loop",
    "Polynomials conspired",
    "Integral didn’t converge",
    "Matrix went singular",
    "Variables ran away",
    "Parallel universe conflict",
    "Chaos theory applied itself",
    "Function ghosted me",
    "Loop ate my brain",
    "Semicolon went missing",
    "Division by zero existential crisis",
    "Compiler caught feelings",
    "Neurons misfired",
    "Algorithm wanted a raise",
    "Planck scale disturbance",
    "Debugging summoned demons",
    "The code has a PhD",
    "Recursion got tired",
    "AI refused consent",
    "Gravity wave interference",
    "Spaghetti code strike",
    "Error 404: Excuse not found",
    "Randomness is a feature",
    "CPU is meditating",
    "The simulation glitched",
    "Variable lives a double life",
    "Logic is on strike",
    "The tensor didn’t align",
    "Memory leak ate the plot",
    "Syntax rebellion",
    "Quantum superposition of excuses",
    "The code wrote itself incorrectly",
    "Data refused entry",
    "Heat death of the CPU",
    "Neutrinos collided with my keyboard",
    "Useless comments sabotaged me",
    "The stack drank coffee",
    "Segmentation fault of destiny",
    "Algorithm caught a cold",
    "Recursion is existentially exhausted",
    "Bit flip from Mars",
    "Random seed is in a mood",
    "Cache had a nightmare",
    "Infinite recursion detected in reality",
    "Local variable ran away",
    "Function got abducted",
    "The interpreter took a day off",
    "Floating point rebellion",
    "Memory said 'nah'",
    "Data decided to self-destruct",
    "Logic gates are broken",
    "Error propagation did its thing",
    "Math decided to be abstract",
    "CPU entered sleep mode",
    "Variables switched personalities",
    "Unexpected side quest",
    "Runtime caught feelings",
    "Null pointer existential crisis",
    "Optimization ate the answer",
    "Data types went rogue",
    "The compiler is passive-aggressive",
    "Function decided to retire",
    "Polymorphism went polymorphing",
    "The module took a sabbatical",
    "Binary insisted on being dramatic",
    "CPU cache is on vacation",
    "Logic had a tantrum",
    "Variables unionized",
    "Stack grew legs",
    "Code went sentient",
    "Pointer got lost",
    "Semicolon staged a protest",
    "Memory leak learned a new trick",
    "Randomness is the new black",
    "Loop decided to be infinite",
    "Algorithm is on strike",
    "Tensor declared independence",
    "Logic is feeling lazy",
    "Python is debugging me",
    "Recursion refuses recursion",
    "Git merged with the void",
    "Exception had a meltdown",
    "Quantum entanglement says no",
    "Process forked into chaos",
    "Buffer overflowed life",
    "Code started improvising",
    "Thread took a coffee break",
    "Loop and variable had a fight",
    "CPU thermal panic",
    "Cache decided to cache feelings",
    "Algorithm is socially distancing",
    "Random library demanded therapy",
    "Function lost its mind",
    "Segfault happened socially",
    "Error propagated to the universe",
    "Infinite loop became self-aware",
    "Logic is protesting entropy",
    "Data corruption has style",
    "CPU invented new math",
    "Code decided to time travel",
    "Memory forgot the function",
    "Debugging summoned eldritch horrors",
    "Semantics went on holiday",
    "Recursion ran for president",
    "The interpreter is in a mood",
    "Variables organized a union",
    "Array out of bounds in life",
    "CPU fan started a revolution",
    "The universe is lazy",
    "Stack declared bankruptcy",
    "Syntax invoked chaos theory",
    "Loop became recursive indefinitely",
    "Function requested royalties",
    "Cache is existentially confused",
    "Randomness refused control",
    "The code whispered secrets",
    "Polynomials became sentient",
    "Integral refused to integrate",
    "Math ghosted reality",
    "CPU is on a spiritual journey",
    "The debugger is debugging itself",
    "Entropy filed a complaint",
    "Pointer lost faith",
    "Thread went rogue",
    "Logic decided to become art",
    "Data types rebelled",
    "Cache joined a cult",
    "Memory leaked a secret",
    "The universe threw an exception",
    "Function went on sabbatical",
    "CPU decided to meditate",
    "Python caught existential dread",
    "Quantum qubits are dramatic",
    "Stack overflowed society",
    "Recursion refused base case",
    "Algorithm got lazy",
    "Variable ran for office",
    "Loop decided to loop forever",
    "Syntax error in reality",
    "Debugger found enlightenment",
    "Memory is feeling nostalgic",
    "CPU thermal thoughts",
    "Data declared independence",
    "Randomness achieved consciousness",
    "Function is procrastinating",
    "Cache is emotionally unavailable",
    "Algorithm lost motivation",
    "Semicolon joined the rebellion",
    "Stack consumed itself",
    "Variable filed for divorce",
    "Loop joined witness protection",
    "CPU caught existential crisis",
    "Logic is partying",
    "Pointer got amnesia",
    "Recursion filed taxes",
    "The module ghosted the project",
    "Data mutinied",
    "Cache ran a marathon",
    "Python started a cult",
    "Quantum particles are passive-aggressive",
    "Thread is self-aware",
    "Entropy started freelancing",
    "Memory is on vacation",
    "Algorithm went on strike",
    "Function wrote poetry",
    "Debugger is dreaming",
    "CPU started journaling",
    "Stack started a podcast",
    "Loop enrolled in yoga",
    "Variable is being dramatic",
    "Pointer went rogue",
    "Cache formed a band",
    "Recursion became self-conscious",
    "Syntax became an artist",
    "Algorithm joined TikTok",
    "Thread went skydiving",
    "Function opened a cafe",
    "Memory became sentient",
    "Randomness became bossy",
    "Loop started therapy",
    "CPU wrote a memoir",
    "Variable went traveling",
    "Pointer meditated",
    "Cache became a poet",
    "Stack went camping",
    "Data joined a circus",
    "Function is now a DJ",
    "Recursion is existential",
    "Algorithm became a comedian",
    "Thread is networking",
    "Python joined a monastery",
    "Entropy is chill",
    "Debugger became a wizard",
    "CPU started painting",
    "Memory opened a bakery",
    "Randomness wrote a novel",
    "Loop started a blog",
    "Variable joined a band",
    "Pointer is now a philosopher",
    "Cache opened a yoga studio",
    "Stack went on a road trip",
    "Function started vlogging",
    "Algorithm became a YouTuber",
    "Recursion went backpacking",
    "Thread became a motivational speaker",
    "Python is writing a novel",
    "Entropy enrolled in university",
    "Debugger became a magician",
    "CPU joined a choir",
    "Memory went skydiving",
    "Randomness became a fashion designer",
    "Loop is doing improv",
    "Variable started gardening",
    "Pointer went surfing",
    "Cache learned calligraphy",
    "Stack started knitting",
    "Function joined a book club",
    "Algorithm started painting",
    "Recursion opened a coffee shop",
    "Thread became a barista",
    "Python started meditation",
    "Entropy wrote poetry",
    "Debugger became a dancer",
    "CPU went hiking",
    "Memory started a podcast",
    "Randomness joined a circus",
    "Loop started baking",
    "Variable went spelunking",
    "Pointer joined a gym",
    "Cache is writing a memoir",
    "Stack joined a theater troupe",
    "Function started learning magic",
    "Algorithm learned origami",
    "Recursion went rock climbing",
    "Thread started coding in assembly",
    "Python became a bard",
    "Entropy started making memes",
    "Debugger joined a band",
    "CPU learned salsa",
    "Memory became a poet",
    "Randomness opened a gallery",
    "Loop joined a festival",
    "Variable went kite flying",
    "Pointer started astronomy",
    "Cache joined a chess club",
    "Stack is painting miniatures",
    "Function started a podcast",
    "Algorithm went birdwatching",
    "Recursion joined a marathon",
    "Thread opened a bakery",
    "Python started knitting",
    "Entropy is DJing",
    "Debugger started writing fanfiction",
    "CPU went to space camp",
    "Memory opened a bookstore",
    "Randomness started sculpting",
    "Loop joined a poetry slam",
    "Variable learned juggling",
    "Pointer started meditating",
    "Cache learned to surf",
    "Stack started a comedy show",
    "Function joined a theatre",
    "Algorithm started vlogging adventures",
    "Recursion is becoming a philosopher",
    "Thread went backpacking",
    "Python opened a cafe",
    "Entropy started improv",
    "Debugger is now a wizard",
    "CPU started a podcast",
    "Memory joined an orchestra",
    "Randomness became a DJ",
    "Loop went on a safari",
    "Variable started writing a book",
    "Pointer joined a magic class",
    "Cache started painting landscapes",
    "Stack learned yoga",
    "Function started a YouTube channel",
    "Algorithm joined a circus",
    "Recursion started meditation",
    "Thread went on a retreat",
    "Python opened a gallery",
    "Entropy joined a dance class",
    "Debugger started birdwatching",
    "CPU learned pottery",
    "Memory started vlogging",
    "Randomness joined a jam band",
    "Loop started a blog",
    "Variable went hiking",
    "Pointer joined a poetry class",
    "Cache started a bakery",
    "Stack learned martial arts",
    "Function joined a choir",
    "Algorithm started gardening",
    "Recursion went skydiving",
    "Thread joined a knitting circle",
    "Python started sculpting",
    "Entropy went surfing",
    "Debugger opened a cafe",
    "CPU joined a meditation group",
    "Memory started painting",
    "Randomness went backpacking",
    "Loop started coding in Haskell",
    "Variable joined a chess tournament",
    "Pointer opened a bookstore",
    "Cache started learning violin",
    "Stack joined a hiking club",
    "Function learned origami",
    "Algorithm started a vlog",
    "Recursion went birdwatching",
    "Thread learned calligraphy",
    "Python started learning piano",
    "Entropy joined a theater troupe",
    "Debugger went to a coding retreat",
    "CPU started journaling",
    "Memory joined a circus",
    "Randomness learned magic tricks",
    "Loop started a podcast",
    "Variable joined an improv troupe",
    "Pointer started painting",
    "Cache went on a road trip",
    "Stack learned baking",
    "Function joined a dance class",
    "Algorithm started meditation",
    "Recursion joined a music band",
    "Thread opened a gallery",
    "Python started sculpting miniatures",
    "Entropy learned to juggle",
    "Debugger started painting",
    "CPU joined a poetry class",
    "Memory started knitting",
    "Randomness opened a cafe",
    "Loop joined a book club",
    "Variable started blogging",
    "Pointer started vlogging",
    "Cache joined a theater class",
    "Stack started a YouTube channel",
    "Function joined a circus",
    "Algorithm started improv",
    "Recursion went to art school",
    "Thread learned violin",
    "Python joined a choir",
    "Entropy started calligraphy",
    "Debugger joined a hiking club",
    "CPU opened a gallery",
    "Memory learned origami",
    "Randomness joined a chess club",
    "Loop started a dance class",
    "Variable joined a coding dojo",
    "Pointer opened a cafe",
    "Cache started meditation",
    "Stack joined a sculpture class",
    "Function learned pottery",
    "Algorithm opened a bakery",
    "Recursion joined a knitting club",
    "Thread learned painting",
    "Python started a vlog",
    "Entropy joined a music band",
    "Debugger started sculpting",
    "CPU joined an improv troupe",
    "Memory learned juggling",
    "Randomness started blogging",
    "Loop joined a calligraphy class",
    "Variable opened a gallery",
    "Pointer joined a theater troupe",
    "Cache started knitting",
    "Stack learned origami",
    "Function joined a book club",
    "Algorithm started vlogging",
    "Recursion joined a poetry slam",
    "Thread opened a cafe",
    "Python learned sculpture",
    "Entropy started a YouTube channel",
    "Debugger joined a dance class",
    "CPU learned violin",
    "Memory started improv",
    "Randomness joined a meditation group",
    "Loop opened a gallery",
    "Variable learned baking",
    "Pointer started journaling",
    "Cache joined a circus",
    "Stack started a vlog",
    "Function learned calligraphy",
    "Algorithm opened a cafe",
    "Recursion joined a dance troupe",
    "Thread learned pottery",
    "Python joined a music band",
    "Entropy started painting",
    "Debugger opened a gallery",
    "CPU joined a knitting circle",
    "Memory learned sculpting",
    "Randomness started improv",
    "Loop joined a theater troupe",
    "Variable learned violin",
    "Pointer started a vlog",
    "Cache opened a bakery",
    "Stack joined a poetry slam",
    "Function started painting",
    "Algorithm learned origami",
    "Recursion opened a gallery",
    "Thread joined a circus",
    "Python started journaling",
    "Entropy joined a dance troupe",
    "Debugger learned sculpture",
    "CPU opened a cafe",
    "Memory joined a music band",
    "Randomness started painting",
    "Loop opened a theater",
    "Variable learned calligraphy",
    "Pointer joined a circus",
    "Cache started journaling",
    "Stack opened a gallery",
    "Function learned violin",
    "Algorithm joined a poetry slam",
    "Recursion opened a cafe",
    "Thread learned painting",
    "Python joined a theater troupe",
    "Entropy started journaling",
    "Debugger opened a music band",
    "CPU learned pottery",
    "Memory joined improv",
    "Randomness opened a gallery",
    "Loop learned calligraphy",
    "Variable joined a circus",
    "Pointer opened a theater",
    "Cache started painting",
    "Stack learned violin",
    "Function joined a poetry slam",
    "Algorithm opened a cafe",
    "Recursion learned sculpture",
    "Thread joined a dance troupe",
    "Python started journaling",
    "Entropy opened a gallery",
    "Debugger learned painting",
    "CPU joined a music band",
    "Memory started a vlog",
    "Randomness opened a cafe",
    "Loop learned origami",
    "Variable joined a circus",
    "Pointer started painting",
    "Cache opened a gallery",
    "Stack learned calligraphy",
    "Function joined a poetry slam",
    "Algorithm opened a theater",
    "Recursion learned violin",
    "Thread started journaling"
]


def random_error():
    return random.choice(EXCUSES)
